export const iconMap: Record<string, string> = {
  // Obst
  'apfel': '🍎', 'äpfel': '🍎', 'grüner apfel': '🍏',
  'banane': '🍌', 'bananen': '🍌',
  'orange': '🍊', 'orangen': '🍊', 'mandarine': '🍊', 'mandarinen': '🍊', 'clementine': '🍊',
  'zitrone': '🍋', 'zitronen': '🍋',
  'erdbeere': '🍓', 'erdbeeren': '🍓',
  'traube': '🍇', 'trauben': '🍇', 'weintrauben': '🍇',
  'birne': '🍐', 'birnen': '🍐',
  'kirsche': '🍒', 'kirschen': '🍒',
  'pfirsich': '🍑', 'nektarine': '🍑',
  'wassermelone': '🍉', 'melone': '🍈', 'honigmelone': '🍈',
  'ananas': '🍍', 'mango': '🥭',
  'kiwi': '🥝', 'avocado': '🥑', 'kokosnuss': '🥥',
  'heidelbeeren': '🫐', 'blaubeeren': '🫐',
  'himbeeren': '🫐', 'johannisbeeren': '🫐', 'brombeeren': '🫐',
  'limette': '🍋‍🟩', 'limetten': '🍋‍🟩',
  'pflaume': '🍑', 'pflaumen': '🍑', 'zwetschge': '🍑', 'zwetschgen': '🍑',
  'granatapfel': '🍎', 'feige': '🍇', 'feigen': '🍇',
  'maracuja': '🥭', 'passionsfrucht': '🥭', 'litschi': '🍑',
  'grapefruit': '🍊', 'pomelo': '🍊',
  'datteln': '🌴', 'cranberries': '🫐', 'rosinen': '🍇',
  'trockenobst': '🍇', 'obstmischung': '🍎',

  // Gemüse
  'tomate': '🍅', 'tomaten': '🍅', 'cherrytomaten': '🍅', 'cocktailtomaten': '🍅',
  'kartoffel': '🥔', 'kartoffeln': '🥔', 'süßkartoffel': '🍠', 'süßkartoffeln': '🍠',
  'karotte': '🥕', 'karotten': '🥕', 'möhre': '🥕', 'möhren': '🥕',
  'brokkoli': '🥦', 'broccoli': '🥦',
  'salat': '🥬', 'kopfsalat': '🥬', 'eisbergsalat': '🥬', 'feldsalat': '🥬',
  'rucola': '🥬', 'romana': '🥬', 'blattsalat': '🥬', 'radicchio': '🥬',
  'gurke': '🥒', 'gurken': '🥒', 'salatgurke': '🥒',
  'paprika': '🫑', 'peperoni': '🌶️',
  'aubergine': '🍆', 'auberginen': '🍆',
  'mais': '🌽', 'maiskolben': '🌽',
  'pilz': '🍄', 'pilze': '🍄', 'champignon': '🍄', 'champignons': '🍄',
  'steinpilze': '🍄', 'pfifferlinge': '🍄', 'shiitake': '🍄', 'austernpilze': '🍄',
  'knoblauch': '🧄', 'knoblauchzehe': '🧄',
  'zwiebel': '🧅', 'zwiebeln': '🧅', 'schalotte': '🧅', 'schalotten': '🧅',
  'rote zwiebel': '🧅', 'frühlingszwiebel': '🧅', 'frühlingszwiebeln': '🧅',
  'chili': '🌶️', 'chilischote': '🌶️', 'jalapeño': '🌶️',
  'ingwer': '🫚',
  'spinat': '🥬', 'babyspinat': '🥬', 'mangold': '🥬', 'grünkohl': '🥬', 'pak choi': '🥬',
  'zucchini': '🥒',
  'kürbis': '🎃', 'hokkaido': '🎃', 'butternut': '🎃',
  'blumenkohl': '🥦', 'romanesco': '🥦',
  'lauch': '🥬', 'porree': '🥬',
  'sellerie': '🥬', 'staudensellerie': '🥬', 'knollensellerie': '🥬',
  'radieschen': '🥕', 'rettich': '🥕', 'meerrettich': '🥕',
  'erbsen': '🫛', 'zuckerschoten': '🫛', 'edamame': '🫛',
  'bohnen': '🫘', 'grüne bohnen': '🫘', 'kidneybohnen': '🫘', 'weiße bohnen': '🫘',
  'kohl': '🥬', 'rotkohl': '🥬', 'weißkohl': '🥬', 'wirsing': '🥬', 'chinakohl': '🥬',
  'kohlrabi': '🥬', 'rosenkohl': '🥬',
  'fenchel': '🥬', 'artischocke': '🥬',
  'rote bete': '🥕', 'rote beete': '🥕',
  'spargel': '🥒', 'grüner spargel': '🥒',
  'oliven': '🫒', 'kapern': '🫒',

  // Brot & Backwaren
  'brot': '🍞', 'brötchen': '🥖', 'semmeln': '🥖',
  'croissant': '🥐', 'brezel': '🥨', 'laugenbrezel': '🥨',
  'toast': '🍞', 'toastbrot': '🍞', 'sandwich': '🥪',
  'baguette': '🥖', 'ciabatta': '🥖',
  'vollkornbrot': '🍞', 'roggenbrot': '🍞', 'dinkelbrot': '🍞', 'pumpernickel': '🍞',
  'knäckebrot': '🍞', 'tortilla': '🫓', 'wrap': '🫓', 'wraps': '🫓',
  'pita': '🫓', 'pitabrot': '🫓', 'naan': '🫓', 'fladenbrot': '🫓',
  'pizzateig': '🍕', 'blätterteig': '🥐', 'hefeteig': '🍞',

  // Milchprodukte
  'milch': '🥛', 'vollmilch': '🥛', 'fettarme milch': '🥛', 'hafermilch': '🥛',
  'mandelmilch': '🥛', 'sojamilch': '🥛', 'kokosmilch': '🥥',
  'käse': '🧀', 'butter': '🧈', 'margarine': '🧈',
  'ei': '🥚', 'eier': '🥚',
  'joghurt': '🥛', 'naturjoghurt': '🥛', 'fruchtjoghurt': '🥛', 'griechischer joghurt': '🥛',
  'sahne': '🥛', 'schlagsahne': '🥛', 'sprühsahne': '🥛',
  'quark': '🥛', 'magerquark': '🥛', 'speisequark': '🥛',
  'frischkäse': '🧀', 'mascarpone': '🧀', 'ricotta': '🧀',
  'mozzarella': '🧀', 'burrata': '🧀',
  'parmesan': '🧀', 'pecorino': '🧀', 'grana padano': '🧀',
  'gouda': '🧀', 'emmentaler': '🧀', 'edamer': '🧀', 'cheddar': '🧀',
  'feta': '🧀', 'hirtenkäse': '🧀', 'schafskäse': '🧀', 'ziegenkäse': '🧀',
  'camembert': '🧀', 'brie': '🧀', 'gorgonzola': '🧀', 'blauschimmelkäse': '🧀',
  'schmand': '🥛', 'saure sahne': '🥛',
  'crème fraîche': '🥛', 'creme fraiche': '🥛',
  'skyr': '🥛', 'kefir': '🥛', 'buttermilch': '🥛',
  'pudding': '🍮', 'milchreis': '🍚',

  // Fleisch & Wurst
  'hähnchen': '🍗', 'huhn': '🍗', 'hühnchen': '🍗', 'hähnchenbrust': '🍗',
  'hähnchenkeule': '🍗', 'hähnchenflügel': '🍗', 'hühnerbrust': '🍗',
  'steak': '🥩', 'rindfleisch': '🥩', 'rindersteak': '🥩', 'rinderhack': '🥩',
  'schweinefleisch': '🥩', 'schweinefilet': '🥩', 'schnitzel': '🥩', 'kotelett': '🥩',
  'hackfleisch': '🥩', 'gehacktes': '🥩', 'hack': '🥩', 'mett': '🥩', 'tatar': '🥩',
  'gulasch': '🥩', 'braten': '🥩', 'filet': '🥩', 'lammfleisch': '🥩', 'lamm': '🥩',
  'wurst': '🌭', 'würstchen': '🌭', 'wiener': '🌭', 'bratwurst': '🌭',
  'speck': '🥓', 'bacon': '🥓',
  'schinken': '🥓', 'kochschinken': '🥓', 'rohschinken': '🥓', 'parmaschinken': '🥓',
  'salami': '🌭', 'mortadella': '🌭', 'leberwurst': '🌭', 'aufschnitt': '🌭',
  'putenbrust': '🍗', 'pute': '🍗', 'truthahn': '🍗', 'ente': '🍗',
  'lachs': '🐟', 'lachsfilet': '🐟',
  'fisch': '🐟', 'forelle': '🐟', 'kabeljau': '🐟', 'pangasius': '🐟', 'seelachs': '🐟',
  'thunfisch': '🐟', 'dorade': '🐟', 'zander': '🐟', 'hering': '🐟', 'makrele': '🐟',
  'garnelen': '🦐', 'shrimps': '🦐', 'krabben': '🦐', 'scampi': '🦐',
  'muscheln': '🦪', 'tintenfisch': '🦑', 'calamari': '🦑',
  'tofu': '🧈', 'tempeh': '🧈', 'seitan': '🧈',

  // Getränke
  'wasser': '💧', 'mineralwasser': '💧', 'sprudelwasser': '💧',
  'saft': '🧃', 'orangensaft': '🧃', 'apfelsaft': '🧃', 'traubensaft': '🧃',
  'multivitaminsaft': '🧃', 'tomatensaft': '🧃', 'smoothie': '🧃',
  'kaffee': '☕', 'espresso': '☕', 'kaffeebohnen': '☕',
  'tee': '🍵', 'grüner tee': '🍵', 'schwarzer tee': '🍵', 'kräutertee': '🍵',
  'kamillentee': '🍵', 'pfefferminztee': '🍵',
  'bier': '🍺', 'weizenbier': '🍺', 'pils': '🍺',
  'wein': '🍷', 'rotwein': '🍷', 'weißwein': '🍾', 'prosecco': '🍾', 'sekt': '🍾',
  'cola': '🥤', 'fanta': '🥤', 'sprite': '🥤',
  'limo': '🥤', 'limonade': '🥤', 'eistee': '🥤',
  'sprudel': '💧', 'selters': '💧',
  'milchshake': '🥛', 'kakaogetränk': '🥛',
  'sirup': '🍯', 'energydrink': '🥤',

  // Grundnahrungsmittel & Beilagen
  'reis': '🍚', 'basmatireis': '🍚', 'jasminreis': '🍚', 'risottoreis': '🍚',
  'wildreis': '🍚', 'sushireis': '🍚',
  'nudeln': '🍝', 'pasta': '🍝', 'spaghetti': '🍝', 'penne': '🍝', 'fusilli': '🍝',
  'tagliatelle': '🍝', 'farfalle': '🍝', 'rigatoni': '🍝', 'linguine': '🍝',
  'makkaroni': '🍝', 'lasagneplatten': '🍝', 'gnocchi': '🍝',
  'couscous': '🌾', 'bulgur': '🌾', 'quinoa': '🌾', 'hirse': '🌾', 'polenta': '🌾',
  'grieß': '🌾', 'amaranth': '🌾',
  'mehl': '🌾', 'weizenmehl': '🌾', 'dinkelmehl': '🌾', 'vollkornmehl': '🌾',
  'speisestärke': '🌾', 'maisstärke': '🌾', 'kartoffelstärke': '🌾',
  'zucker': '🍬', 'rohrzucker': '🍬', 'puderzucker': '🍬', 'brauner zucker': '🍬',
  'salz': '🧂', 'meersalz': '🧂', 'fleur de sel': '🧂',
  'pfeffer': '🫙', 'schwarzer pfeffer': '🫙',
  'öl': '🫒', 'olivenöl': '🫒', 'sonnenblumenöl': '🫒', 'rapsöl': '🫒',
  'sesamöl': '🫒', 'kokosöl': '🫒', 'erdnussöl': '🫒', 'trüffelöl': '🫒',
  'essig': '🫗', 'balsamico': '🫗', 'balsamicoessig': '🫗', 'apfelessig': '🫗',
  'weißweinessig': '🫗', 'rotweinessig': '🫗', 'reisessig': '🫗',
  'honig': '🍯', 'ahornsirup': '🍯', 'agavendicksaft': '🍯',
  'marmelade': '🍓', 'konfitüre': '🍓', 'gelee': '🍓',
  'nutella': '🍫', 'nussnougatcreme': '🍫', 'erdnussbutter': '🥜',
  'haferflocken': '🥣', 'müsli': '🥣', 'cornflakes': '🥣', 'granola': '🥣',
  'porridge': '🥣',

  // Konserven & Fertigprodukte
  'dose': '🥫', 'dosentomaten': '🥫', 'gehackte tomaten': '🥫',
  'kichererbsen': '🥫', 'linsen': '🥫', 'rote linsen': '🥫', 'belugalinsen': '🥫',
  'passierte tomaten': '🥫', 'stückige tomaten': '🥫',
  'tomatenmark': '🥫', 'tomatensoße': '🥫',
  'mais (dose)': '🥫', 'erbsen (dose)': '🥫',
  'kokosmilch (dose)': '🥫', 'kokoscreme': '🥫',
  'brühe': '🍲', 'gemüsebrühe': '🍲', 'hühnerbrühe': '🍲', 'rinderbrühe': '🍲',
  'fond': '🍲', 'bouillon': '🍲',
  'pesto': '🌿', 'basilikumpesto': '🌿',
  'soße': '🫗', 'nudelsoße': '🫗',

  // Gewürze & Kräuter
  'basilikum': '🌿', 'petersilie': '🌿', 'oregano': '🌿',
  'thymian': '🌿', 'rosmarin': '🌿', 'dill': '🌿', 'schnittlauch': '🌿',
  'koriander': '🌿', 'minze': '🌿', 'salbei': '🌿', 'estragon': '🌿',
  'majoran': '🌿', 'lorbeerblatt': '🌿', 'lorbeerblätter': '🌿',
  'zimt': '🫙', 'zimtstange': '🫙',
  'paprikapulver': '🫙', 'cayennepfeffer': '🫙', 'chiliflocken': '🌶️',
  'curry': '🫙', 'currypulver': '🫙', 'currypaste': '🫙', 'garam masala': '🫙',
  'kurkuma': '🫙', 'kreuzkümmel': '🫙', 'kümmel': '🫙', 'kardamom': '🫙',
  'muskat': '🫙', 'muskatnuss': '🫙', 'nelken': '🫙', 'sternanis': '🫙',
  'vanille': '🫙', 'vanilleschote': '🫙', 'vanilleextrakt': '🫙',
  'kräuter der provence': '🌿', 'italienische kräuter': '🌿',

  // Soßen & Dips
  'ketchup': '🍅', 'senf': '🫗', 'senfmittelscharf': '🫗',
  'sojasoße': '🫗', 'sojasauce': '🫗',
  'mayonnaise': '🫗', 'mayo': '🫗', 'remoulade': '🫗',
  'tabasco': '🌶️', 'sriracha': '🌶️', 'sambal oelek': '🌶️', 'harissa': '🌶️',
  'worcestershiresauce': '🫗', 'worcestersauce': '🫗',
  'bbq-soße': '🫗', 'barbecuesoße': '🫗',
  'tzatziki': '🥛', 'hummus': '🫘', 'guacamole': '🥑', 'salsa': '🍅',
  'tahini': '🫙', 'sesampaste': '🫙',
  'fischsoße': '🐟', 'austernsauce': '🐟',
  'miso': '🫙', 'misopaste': '🫙',

  // Snacks & Süßes
  'schokolade': '🍫', 'zartbitterschokolade': '🍫', 'vollmilchschokolade': '🍫',
  'weiße schokolade': '🍫', 'schokoriegel': '🍫',
  'chips': '🥨', 'tortillachips': '🥨', 'nachos': '🥨', 'salzstangen': '🥨',
  'kekse': '🍪', 'cookies': '🍪', 'waffeln': '🧇',
  'gummibärchen': '🍬', 'bonbons': '🍬', 'lakritze': '🍬', 'weingummi': '🍬',
  'eis': '🍦', 'eiscreme': '🍦', 'speiseeis': '🍦',
  'kuchen': '🍰', 'torte': '🎂', 'muffin': '🧁', 'muffins': '🧁',
  'nüsse': '🥜', 'walnüsse': '🥜', 'cashews': '🥜', 'cashewkerne': '🥜',
  'haselnüsse': '🥜', 'pistazien': '🥜', 'pinienkerne': '🥜', 'paranüsse': '🥜',
  'mandeln': '🥜', 'erdnüsse': '🥜', 'macadamia': '🥜',
  'studentenfutter': '🥜', 'nussmischung': '🥜', 'trail mix': '🥜',
  'popcorn': '🍿', 'cracker': '🥨', 'reiswaffeln': '🥨',
  'müsliriegel': '🥣', 'proteinriegel': '🥣',

  // Fertiggerichte & Internationales
  'pizza': '🍕', 'tiefkühlpizza': '🍕',
  'sushi': '🍣', 'ramen': '🍜', 'udon': '🍜',
  'curry (gericht)': '🍛', 'dhal': '🍛',
  'falafel': '🧆', 'gyoza': '🥟', 'dim sum': '🥟', 'spring rolls': '🥟',
  'tacos': '🌮', 'burrito': '🌯', 'döner': '🥙', 'kebab': '🥙',
  'burger': '🍔', 'hamburger': '🍔',
  'hot dog': '🌭', 'pommes': '🍟', 'fritten': '🍟',
  'pfannkuchen': '🥞', 'crêpe': '🥞', 'pancake': '🥞',

  // Backen
  'backpulver': '🧁', 'natron': '🧁',
  'hefe': '🍞', 'trockenhefe': '🍞', 'frische hefe': '🍞',
  'gelatine': '🫙', 'agar-agar': '🫙',
  'vanillezucker': '🍬', 'vanillinzucker': '🍬',
  'kakao': '🍫', 'kakaopulver': '🍫', 'backkakao': '🍫',
  'schokodrops': '🍫', 'schokostückchen': '🍫',
  'kokosraspel': '🥥', 'kokosflocken': '🥥',
  'mandelstifte': '🥜', 'mandelmehl': '🥜',
  'sahnesteif': '🫙', 'tortenguss': '🫙',
  'lebensmittelfarbe': '🎨', 'fondant': '🎂',
  'marzipan': '🍬', 'nougat': '🍫',

  // Haushalt & Pflege
  'toilettenpapier': '🧻', 'klopapier': '🧻', 'küchenrolle': '🧻',
  'spülmittel': '🧴', 'geschirrspülmittel': '🧴', 'spültabs': '🧴',
  'waschmittel': '🧴', 'weichspüler': '🧴',
  'seife': '🧼', 'handseife': '🧼', 'flüssigseife': '🧼',
  'zahnpasta': '🪥', 'zahnbürste': '🪥', 'mundspülung': '🪥',
  'taschentücher': '🤧', 'feuchttücher': '🤧',
  'müllbeutel': '🗑️', 'müllsäcke': '🗑️',
  'alufolie': '📄', 'frischhaltefolie': '📄', 'backpapier': '📄',
  'schwamm': '🧽', 'schwämme': '🧽', 'lappen': '🧽',
  'duschgel': '🧴', 'shampoo': '🧴', 'conditioner': '🧴', 'bodylotion': '🧴',
  'deo': '🧴', 'deodorant': '🧴', 'rasierer': '🪒',
  'kerze': '🕯️', 'kerzen': '🕯️', 'teelichter': '🕯️',
  'batterien': '🔋', 'glühbirne': '💡',
  'handcreme': '🧴', 'sonnencreme': '🧴',
};

const categoryIcons: Record<string, string> = {
  'Obst & Gemüse': '🥬',
  'Milchprodukte': '🧀',
  'Fleisch & Fisch': '🥩',
  'Backwaren': '🥖',
  'Getränke': '🥤',
  'Tiefkühl': '🧊',
  'Konserven': '🥫',
  'Gewürze & Soßen': '🌿',
  'Snacks & Süßes': '🍫',
  'Grundnahrungsmittel': '🌾',
  'Haushalt': '🧴',
  'Sonstiges': '📦',
};

export const categories = [
  'Obst & Gemüse',
  'Milchprodukte',
  'Fleisch & Fisch',
  'Backwaren',
  'Getränke',
  'Tiefkühl',
  'Konserven',
  'Gewürze & Soßen',
  'Snacks & Süßes',
  'Grundnahrungsmittel',
  'Haushalt',
  'Sonstiges',
];

export function getItemIcon(name?: string, customIcon?: string | null): string {
  if (customIcon) return customIcon;
  if (!name) return '📦';
  const lower = name.toLowerCase().trim();
  if (iconMap[lower]) return iconMap[lower];
  // Partial match
  for (const [key, icon] of Object.entries(iconMap)) {
    if (lower.includes(key) || key.includes(lower)) return icon;
  }
  return '📦';
}

export function getCategoryIcon(category?: string | null): string {
  if (!category) return '📦';
  return categoryIcons[category] || '📦';
}

export function getCategoryColor(category?: string | null): string {
  const colors: Record<string, string> = {
    'Obst & Gemüse': 'bg-green-100 dark:bg-green-900/40 text-green-900 dark:text-green-100',
    'Milchprodukte': 'bg-blue-100 dark:bg-blue-900/40 text-blue-900 dark:text-blue-100',
    'Fleisch & Fisch': 'bg-red-100 dark:bg-red-900/40 text-red-900 dark:text-red-100',
    'Backwaren': 'bg-amber-100 dark:bg-amber-900/40 text-amber-900 dark:text-amber-100',
    'Getränke': 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-900 dark:text-cyan-100',
    'Tiefkühl': 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-900 dark:text-indigo-100',
    'Konserven': 'bg-orange-100 dark:bg-orange-900/40 text-orange-900 dark:text-orange-100',
    'Gewürze & Soßen': 'bg-yellow-100 dark:bg-yellow-900/40 text-yellow-900 dark:text-yellow-100',
    'Snacks & Süßes': 'bg-pink-100 dark:bg-pink-900/40 text-pink-900 dark:text-pink-100',
    'Grundnahrungsmittel': 'bg-stone-100 dark:bg-stone-900/40 text-stone-900 dark:text-stone-100',
    'Haushalt': 'bg-gray-200 dark:bg-gray-800 text-gray-900 dark:text-gray-100',
    'Sonstiges': 'bg-violet-100 dark:bg-violet-900/40 text-violet-900 dark:text-violet-100',
  };
  return colors[category || ''] || colors['Sonstiges'];
}
